### PR TITLE
To Nix flake

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
Nix flakes allows to use the script in a single command:

```
nix run github:svanderburg/nix-patchtools
```

This PR implements the Nix packaging as a Nix flake.
It is still possible to use standard Nix with the root `default.nix`

### CODE REVIEW

**Comment by rollschild** [comment]
Hey, I'm curious what's the status of this PR? Could be useful to my current work. Thanks!

**Comment by GuillaumeDesforges** [comment]
@rollschild no sign of life from @svanderburg ...

You could still use my fork

```
nix run github:GuillaumeDesforges/nix-patchtools FILE
```

**Comment by GuillaumeDesforges** [comment]
@svanderburg gentle ping

**Comment by Kreijstal** [comment]
@GuillaumeDesforges can you enable issues on your fork

**Comment by GuillaumeDesforges** [comment]
@Kreijstal done

**Pull request closed without merging**
